# This file was generated by GoReleaser. DO NOT EDIT.
cask "calendar-sync" do
  version "2.1.3"

  on_macos do
    on_intel do
      sha256 "9f7b21643346eedf40ccde604f57d1f5cca2ad2c8893fbf0f372844f0679744a"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "008800c2e4613812a7a7c812bb2d00f6aed858995d78d25ab775857a4a96f03d"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d655a21aa8e86393ecb438ce9d5cda26360c17b112a55d1b73b8b0ef5ea7ad74"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0161e71ec2bbf006936c80aabdabeae27cc54cf7c0f75aae5e31fbceac21eb47"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "calendar-sync"
  desc "Google Calendar event mirroring tool"
  homepage "https://github.com/tammersaleh/calendar-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "calendar-sync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/calendar-sync"]
    end
  end

  # No zap stanza required

end
