# This file was generated by GoReleaser. DO NOT EDIT.
cask "calendar-sync" do
  version "2.1.2"

  on_macos do
    on_intel do
      sha256 "8fe0a705bf82f8398c8226c02d9a8558a738a8753f36423749d9222ea3f4426a"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dcdae6f91beae6302410195f4a17f38392b3dcf0003993418374428eccf5178d"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec9d0f934bbb7f526395b66c686c6727950603d9bcfd46c6e5c0549b01e1fc5d"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2bb8c1272058bedffb20db34a9f3356ecb94ca557cedfaf5447a855ffe61f527"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "calendar-sync"
  desc "Google Calendar event mirroring tool"
  homepage "https://github.com/tammersaleh/calendar-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "calendar-sync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/calendar-sync"]
    end
  end

  # No zap stanza required

end
