# This file was generated by GoReleaser. DO NOT EDIT.
cask "calendar-sync" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "10b2763e36f91379986c9ca039ada5a9afb5b7b716c734e4711dc4668d414b60"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b9c9b4a7f4f9ed8335598a609ad6c014007ce7d688f92050a2042cc8b9bece9"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a4eec8a4d83d195dbc37979a9008fd31effae4936344cc5dec8ba1a19b1540e"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2c82fff15fdb7f6226dae8aa8a34b79932c16de2e138130f406f7b9d8c49d5b7"
      url "https://github.com/tammersaleh/calendar-sync/releases/download/v#{version}/calendar-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "calendar-sync"
  desc "Google Calendar event mirroring tool"
  homepage "https://github.com/tammersaleh/calendar-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "calendar-sync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/calendar-sync"]
    end
  end

  # No zap stanza required

end
