# This file was generated by GoReleaser. DO NOT EDIT.
cask "confluence-cli" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "165bdcbaf77575c340969c2cb7aac9f47a7f87fbcc99dc489dc528ff1b226d62"
      url "https://github.com/tammersaleh/confluence-sync/releases/download/v#{version}/confluence-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a184257af1c9f94f4fc0a56f8aa5d990a133efb4a4922dcf209f3459c37b894b"
      url "https://github.com/tammersaleh/confluence-sync/releases/download/v#{version}/confluence-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b602b5b9ce97ae0683e6ad72690a77aa5517e448f5cfdd0e806cb76a320d06a9"
      url "https://github.com/tammersaleh/confluence-sync/releases/download/v#{version}/confluence-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6348209ba44398796249270e550277c371fb852d77b3f77de3638f661c19207a"
      url "https://github.com/tammersaleh/confluence-sync/releases/download/v#{version}/confluence-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "confluence-cli"
  desc "Agent-first Confluence CLI"
  homepage "https://github.com/tammersaleh/confluence-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "confluence"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/confluence"]
    end
  end

  # No zap stanza required

end
