# This file was generated by GoReleaser. DO NOT EDIT.
cask "confluence-cli" do
  version "2.2.0"

  on_macos do
    on_intel do
      sha256 "ef092d45b579730a30eb7ed921af8506031b970e021b1adef798ee193e466523"
      url "https://github.com/tammersaleh/confluence-cli/releases/download/v#{version}/confluence-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5bd6174f00d982520b400c7b8457a6b928e1b5d5806d341fcbd578da3f8f567d"
      url "https://github.com/tammersaleh/confluence-cli/releases/download/v#{version}/confluence-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eebabf382877a3dc0405492f133745eee3c7c55b0dbf88890da5e22a7dc52b00"
      url "https://github.com/tammersaleh/confluence-cli/releases/download/v#{version}/confluence-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ddece696465c195a455511e80f571a54a4aafd4a86d9f6fb8ad05fca79fb88c1"
      url "https://github.com/tammersaleh/confluence-cli/releases/download/v#{version}/confluence-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "confluence-cli"
  desc "Agent-first Confluence CLI"
  homepage "https://github.com/tammersaleh/confluence-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "confluence"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/confluence"]
    end
  end

  # No zap stanza required

end
