# This file was generated by GoReleaser. DO NOT EDIT.
cask "confluence-cli" do
  version "1.10.0"

  on_macos do
    on_intel do
      sha256 "1b46413d886a6ec585b54a6b809b79b7b87f018f2a2ba7d48c2205581524b4e2"
      url "https://github.com/tammersaleh/confluence-cli/releases/download/v#{version}/confluence-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d9fea0c4825f174fa3905c82ca3345f21f42f74fdb09be90a0d8606378a1cba5"
      url "https://github.com/tammersaleh/confluence-cli/releases/download/v#{version}/confluence-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6090b23835d4fd75583cda6d5ec37356ee38f173449d386b3608edca5a92a8e7"
      url "https://github.com/tammersaleh/confluence-cli/releases/download/v#{version}/confluence-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "015ee15800d39969e06f4b40dd3c448d11adda50e08e8838c0467e2c4fbb04c5"
      url "https://github.com/tammersaleh/confluence-cli/releases/download/v#{version}/confluence-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "confluence-cli"
  desc "Agent-first Confluence CLI"
  homepage "https://github.com/tammersaleh/confluence-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "confluence"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/confluence"]
    end
  end

  # No zap stanza required

end
