# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotfiles-manager" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "486d4fc49ed70078e0b3dc5fc0ef5b182028fb8a4735d361e5e8dbcf3dca5deb"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c2fd03c0544595f7ab24f83c6f5bbc8fc3734e8ed2498b81154563b2ea23338e"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9e39908bd15ec1ccc13755e31a0ac6f6890dbac6df6b331faf21e5f29882fbb1"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b1160cd3e2dd0572bda7a508326e5b11e4542027990557c3db9cdcbc8ebad0e"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dotfiles-manager"
  desc "Dotfiles manager - stow and the dotfiles script in one binary"
  homepage "https://github.com/tammersaleh/dotfiles-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dfm"]
    end
  end

  # No zap stanza required
end
