# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotfiles-manager" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "e5b39aeea827e1a4d019d95a31dedc7aa76e9e1227e6b3284ee958bfb3fdcb27"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "86cf8cac1f35b4b1ded2dbfaf485ffa1bbd20e0f42b31718c3ba9346f6553ad1"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "58fa9e6b234f4745e384365c7510a2cfa99bff00e6fc33207e8cd6567e2c424c"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f163247d8e43868e1c8b92bc25df9e61d6f8c43346aed0173b88e3661f4bd72"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dotfiles-manager"
  desc "Dotfiles manager - stow and the dotfiles script in one binary"
  homepage "https://github.com/tammersaleh/dotfiles-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dfm"]
    end
  end

  # No zap stanza required
end
