# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotfiles-manager" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "b4df1ef83cae4ffc2d3c0e5891ec37666a137c8705718756316a46f0e1770e1c"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cf501b40f4d0c68023ced4c26cbc3a091744d9c133def44dffe7b594da82e28a"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8862c66e72fd81b4b1ac3220b215459f7af9606015857947c7c24465bf64b198"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f340f61e07fb7b5daba2463a556000f57902ce4c822d7151b4cdcc185c246765"
      url "https://github.com/tammersaleh/dotfiles-manager/releases/download/v#{version}/dotfiles-manager_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dotfiles-manager"
  desc "Dotfiles manager - stow and the dotfiles script in one binary"
  homepage "https://github.com/tammersaleh/dotfiles-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dfm"]
    end
  end

  # No zap stanza required
end
