# This file was generated by GoReleaser. DO NOT EDIT.
cask "envsec" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "4108ac07f38bcaa11f81ebc5a0f90b42f325245e027d4bde9cd7773d9df0ba16"
      url "https://github.com/tammersaleh/envsec/releases/download/v#{version}/envsec_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7186e3894ff2556b9ae5403e9e3b095d0fe9a2ba24b18e47c7329ce8eee44e9d"
      url "https://github.com/tammersaleh/envsec/releases/download/v#{version}/envsec_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "envsec"
  desc "Export 1Password secrets as environment variables via the macOS keychain"
  homepage "https://github.com/tammersaleh/envsec"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envsec"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envsec"]
    end
  end

  # No zap stanza required
end
