# This file was generated by GoReleaser. DO NOT EDIT.
cask "envsec" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "7f6887f92b7f31a55ebe590cf14c12ebae0f44e44d8fcb0004eec66162410478"
      url "https://github.com/tammersaleh/envsec/releases/download/v#{version}/envsec_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "79a1be815fffe182eaba723309b0d46f3ee12aec107126afc8c5ce9977d4d3f4"
      url "https://github.com/tammersaleh/envsec/releases/download/v#{version}/envsec_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "envsec"
  desc "Export 1Password secrets as environment variables via the macOS keychain"
  homepage "https://github.com/tammersaleh/envsec"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envsec"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envsec"]
    end
  end

  # No zap stanza required
end
