# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-cli" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "0c5d77574bd53eea16e1694b17bff45fe287bb05dcb1cb10abd009a6b0d7736a"
    end
    on_arm do
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "baee56869e41cd913c2f429f89c6708a969ee5276f21d8dd60c7bad7727e4f59"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_linux_amd64.tar.gz"
      sha256 "22353ddd1929572153ca063c80c4f2efc36777d4c69b6fff9d0d09455a9394c7"
    end
    on_arm do
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_linux_arm64.tar.gz"
      sha256 "7dc9561ea2bfd763e0782211e861fa2d49f9e2066ed02d34d1e1d53f9aa7a2cf"
    end
  end

  name "slack-cli"
  desc "Read-only Slack CLI for agents and automation"
  homepage "https://github.com/tammersaleh/slack-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slack"]
    end
  end

  # No zap stanza required

end
