# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-cli" do
  version "3.2.0"

  on_macos do
    on_intel do
      sha256 "c8c3c08a949091c2ea039216ec6589296268302aaf30606245919328b85e1f0c"
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fda43164f376f300281593f5c7efd9186f704101996329bbaa35e941549c9755"
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c49a389a39e65c34bd5e287b7c3b2497ddbc3aadd10e0f1f003f1d3cf0a35a3"
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fc5a37cb677fa7eafcd0b520af0c3fea9db287b54a545f6881f60b1ac267d7d2"
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slack-cli"
  desc "Read-only Slack CLI for agents and automation"
  homepage "https://github.com/tammersaleh/slack-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slack"]
    end
  end

  # No zap stanza required

end
