# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-cli" do
  version "5.0.2"

  on_macos do
    on_arm do
      sha256 "c94b13d1cc4170eea29d9ed1c8be1f646dcf69ba674a136fae1cf2e125288835"
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aaaaeafafbdcfeead52ad9cc616bb2e4c07dd0304148f37bf6d0c14c798ac253"
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "691df861d6d0c36a9da2cdb03a12fe49df610d14f4e61402a74e07255d616e45"
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9db869388c0a403d7072553cb31820153d29dcdc1f4f67315bd5ecacb4218c0b"
      url "https://github.com/tammersaleh/slack-cli/releases/download/v#{version}/slack-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "slack-cli"
  desc "Read-only Slack CLI for agents and automation"
  homepage "https://github.com/tammersaleh/slack-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slack"]
    end
  end

  # No zap stanza required
end
